export enum RiskLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL'
}

export enum CauseCategory {
  REAL_BUG = 'REAL_BUG',
  INCORRECT_USE = 'INCORRECT_USE',
  PRODUCT_LIMITATION = 'PRODUCT_LIMITATION',
  CONFIGURATION_ERROR = 'CONFIGURATION_ERROR',
  INDETERMINATE = 'INDETERMINATE'
}